spring.application.name=demo
spring.threads.virtual.enabled=true
server.forward-headers-strategy=framework

# Использование SQLite в оперативной памяти (In-Memory)
spring.datasource.url=JDBC:sqlite::memory:
spring.datasource.driver-class-name=org.sqlite.JDBC

# Диалект Hibernate для генерации правильного SQL под SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Автоматическое создание/обновление таблиц при старте
spring.jpa.hibernate.ddl-auto=update

# Отключаем спам SQL-запросов в консоль
spring.jpa.show-sql=false